# Meta Data for SEO

## Homepage
title = "AWS re:Security"
titleSeparator = "-"
titleAddition = "Welcome"
description = "AWS re:Security is an open source interactive learning platform that helps develop skills in the fields of Cloud Security and Blue Team"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["og-main.png"]
ogLocale = "en_US"
domainTLD = "awsresecurity.com"
titleHome = "AWS re:Security"

## Twitter Cards
twitterSite = "@gerardokaztro"
twitterCreator = "@gerardokaztro"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "AWS Security LATAM"
schemaAuthor = "Gerardo Castro"
schemaAuthorTwitter = "https://twitter.com/gerardokaztro"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/gerardokaztro"
schemaAuthorGitHub = "https://github.com/gerardokaztro"
schemaLocale = "en-US"
schemaLogo = "js-main.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "og-main.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/gerardokaztro/awsresecurity"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "This is NOT an official AWS website.</br> Built by <a href=\"https://gerardokaztro.com/\">@gerardokaztro</a> in partnership with <a href=\"https://www.meetup.com/es/awssecuritylatam/\">AWS Security LATAM</a>."

# Feed
copyRight = "2022 © Gerardo Castro. All Rights Reserved."

# Alert
alert = true
alertDismissable = true
alertText = "Many more people should know about this free learning platform. Please <a class=\"alert-link stretched-link\" href=\"https://twitter.com/intent/tweet/?text=%23AWSreSecurity%20an%20interactive%20training%20platform%20to%20learn%20%23Security%20using%20%40aws_cloud%20by%20%40gerardokaztro.%20Check%20it%20out%20&url=https://main.d23jt5avp6hirf.amplifyapp.com/en\" target=\"_blank\" rel=\"noopener\">👉 Twittea 👈</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/gerardokaztro/awsresecurity"
docsRepoBranch = "main"
docsRepoSubPath = "public"
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = ["docs"]
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
