[[docs]]
  name = "Overview"
  weight = 10
  identifier = "overview"
  url = "/docs/overview/"

[[docs]]
  name = "Fundamentos"
  weight = 20
  identifier = "fundamentos"
  url = "/docs/fundamentos/"

[[docs]]
  name = "Identidad y Federacion"
  weight = 30
  identifier = "identidad"
  url = "/docs/identidad/"

[[docs]]
  name = "Deteccion de amenazas"
  weight = 40
  identifier = "deteccion"
  url = "/docs/deteccion/"

[[docs]]
  name = "Registro y monitoreo"
  weight = 50
  identifier = "monitoreo"
  url = "/docs/monitoreo/"

[[docs]]
  name = "Repuesta ante incidentes"
  weight = 60
  identifier = "respuesta"
  url = "/docs/respuesta/"

[[docs]]
  name = "Proteccion de la infraestructura"
  weight = 70
  identifier = "infraestructura"
  url = "/docs/infrasec/"

[[docs]]
  name = "Proteccion de los datos"
  weight = 80
  identifier = "datos"
  url = "/docs/datasec/"

[[docs]]
  name = "DevSecOps"
  weight = 90
  identifier = "devsecops"
  url = "/docs/devsecops/"

[[docs]]
  name = "Otros dominios"
  weight = 100
  identifier = "otros"
  url = "/docs/otros/"

[[docs]]
  name = "Final"
  weight = 150
  identifier = "final"
  url = "/docs/final/"

[[main]]
  name = "📚 Documentación"
  url = "/docs/overview/introduccion/"
  weight = 10

[[main]]
  name = "✍ Blog"
  url = "https://medium.com/@gerardokaztro"
  weight = 20

[[main]]
  name = "🤝  Comunidad"
  url = "https://awssecuritycommunity.slack.com/join/shared_invite/zt-1cekzassk-48CNafIjBFiPWkGdIDzfeA/"
  weight = 30
  identifier = "comunidad"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/gerardokaztro"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/gerardokaztro"
  weight = 20

[[footer]]
  name = "Contáctenos"
  url = "/contacto/"
  weight = 10

[[footer]]
  name = "Reporte un problema"
  url = "/problema/"
  weight = 20

[[footer]]
  name = "Legal"
  url = "/legal/"
  weight = 30